"""Initial migration

Revision ID: aa534e4fd60c
Revises: 
Create Date: 2025-12-01 23:08:53.045477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa534e4fd60c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'EMPLOYEE', name='Role', create_type=False), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_table('Lead',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('frn', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pipelineStatus', postgresql.ENUM('Unassigned', 'Email_Sent', 'Client_Replied', 'Plan_Sent', 'Rate_Finalized', 'Docs_Signed', 'Testing', 'Approved', 'Rejected', name='PipelineStatus', create_type=False), nullable=False),
    sa.Column('history', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('assignedEmployeeId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignedEmployeeId'], ['User.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Lead_assignedEmployeeId'), 'Lead', ['assignedEmployeeId'], unique=False)
    op.create_index(op.f('ix_Lead_frn'), 'Lead', ['frn'], unique=True)
    op.create_index(op.f('ix_Lead_pipelineStatus'), 'Lead', ['pipelineStatus'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Lead_pipelineStatus'), table_name='Lead')
    op.drop_index(op.f('ix_Lead_frn'), table_name='Lead')
    op.drop_index(op.f('ix_Lead_assignedEmployeeId'), table_name='Lead')
    op.drop_table('Lead')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
